In [1]:
import numpy as np

31. How to ignore all numpy warnings (not recommended)

warnings.filterwarnings('ignore')

32. Is the following expressions true?
np.sqrt(-1) == np.emath.sqrt(-1)
its False

33. How to get the dates of yesterday, today and tomorrow?

In [16]:
today = np.datetime64("today", "D")
yesterday = np.datetime64("today", "D") - np.timedelta64(1, "D")
tomorrow =np.datetime64("today", "D") + np.timedelta64(1, "D")

In [17]:
print(today)
print(yesterday)
print(tomorrow)

2024-02-24
2024-02-23
2024-02-25


34. How to get all the dates corresponding to the month of July 2016? 

In [18]:
july_dates = np.arange("2016-07","2016-08", dtype = "datetime64[D]")
print(july_dates)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


35. How to compute ((A+B)*(-A/2)) in place (without copy)?

In [30]:
A = np.ones(3, dtype = int)*1
B = np.ones(3, dtype = int)*2
C = ((A+B)*(-A/2))
print(C)


[-1.5 -1.5 -1.5]


36. Extract the integer part of a random array of positive numbers using 4 different methods

In [37]:
np.random.seed(0)
Z = np.random.uniform(0,10,10)
print(Z)

print (np.floor(Z))
print (np.ceil(Z)-1)
print (Z.astype(int))
print (np.trunc(Z))

[5.48813504 7.15189366 6.02763376 5.44883183 4.23654799 6.45894113
 4.37587211 8.91773001 9.63662761 3.83441519]
[5. 7. 6. 5. 4. 6. 4. 8. 9. 3.]
[5. 7. 6. 5. 4. 6. 4. 8. 9. 3.]
[5 7 6 5 4 6 4 8 9 3]
[5. 7. 6. 5. 4. 6. 4. 8. 9. 3.]


37. Create a 5x5 matrix with row values ranging from 0 to 4

In [40]:
x = np.zeros((5,5), dtype = int)
x += np.arange(5)
x

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

38. Consider a generator function that generates 10 integers and use it to build an array

In [50]:
def generator():
    for i in range (10):
        yield i 
x = np.fromiter(generator(), dtype = int, count=-1)
print(x)

[0 1 2 3 4 5 6 7 8 9]


39. Create a vector of size 10 with values ranging from 0 to 1, both excluded

In [86]:
y = np.random.random(10)
y

array([0.9292962 , 0.31856895, 0.66741038, 0.13179786, 0.7163272 ,
       0.28940609, 0.18319136, 0.58651293, 0.02010755, 0.82894003])

In [83]:
x = np.linspace(0,1,12)[1:-1]
x

array([0.09090909, 0.18181818, 0.27272727, 0.36363636, 0.45454545,
       0.54545455, 0.63636364, 0.72727273, 0.81818182, 0.90909091])

40. Create a random vector of size 10 and sort it

In [84]:
y = np.random.randint(30, size = (10))
print (y)
y.sort()
print(y)

[ 7 21  9  0 10 18 11 26 23 27]
[ 0  7  9 10 11 18 21 23 26 27]


41. How to sum a small array faster than np.sum?

In [76]:
Z = np.arange(10)
print(Z)
np.add.reduce(Z)

[0 1 2 3 4 5 6 7 8 9]


45

In [78]:
np.sum(Z)

45

42. Consider two random array A and B, check if they are equal

In [89]:
A = np.random.randint(1,7,8)
B = np.random.randint(1,7,8)
print(A)
print(B)
equal = np.array_equal(A,B)
print(equal)

[4 5 6 1 5 4 6 4]
[5 6 2 6 4 1 1 1]
False


43. Make an array immutable (read-only) 

In [93]:
Z = np.zeros(10)
Z.flags.writeable = False
print(Z)
#Z[0] = 1    you can not change the elements

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates

In [94]:
Z = np.random.random((10,2))
X,Y = Z[:,0], Z[:,1]
R = np.sqrt(X**2+Y**2)
T = np.arctan2(Y,X)
print(R)
print(T)

[1.01495527 0.88399863 0.58090824 0.73406117 0.66822409 0.77181705
 0.84160485 0.88445414 0.36589886 0.55283979]
[1.25707224 0.84238424 0.40808171 1.00282353 0.78038728 0.38238445
 1.0977141  0.11656531 1.3155772  0.06086006]


45. Create random vector of size 10 and replace the maximum value by 0

In [96]:
Z = np.random.randint(1,30,10)
print(Z)
Z[Z.argmax()] = 0
print(Z)

[21 11 23 12  6 29 16  9  3 28]
[21 11 23 12  6  0 16  9  3 28]
