In [2]:
import numpy as np

16. How to add a border (filled with 0's) around an existing array?

In [12]:
x = np.ones((3,3), dtype= int)
print(x)
x = np.pad(x, pad_width = 1, mode = "constant", constant_values = 0)
print(x)

[[1 1 1]
 [1 1 1]
 [1 1 1]]
[[0 0 0 0 0]
 [0 1 1 1 0]
 [0 1 1 1 0]
 [0 1 1 1 0]
 [0 0 0 0 0]]


17. What is the result of the following expression?
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1

nan
False
False
False
True
False

18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [25]:
x = np.diag(1+np.arange(4), k= -1)
x

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

19. Create a 8x8 matrix and fill it with a checkerboard pattern

In [26]:
x = np.zeros ((8,8), dtype=int)
x[1::2, ::2]= 1
x[::2, 1::2] = 1
x

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

print (np.unravel_index(100, (6,7,8)))

21. Create a checkerboard 8x8 matrix using the tile function

In [8]:
x = np.array([[1,0],[1,0]])
print(x)
y = np.tile(array,(4,4))
y

[[1 0]
 [1 0]]


array([[1, 0, 1, 0, 1, 0, 1, 0],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [1, 0, 1, 0, 1, 0, 1, 0]])

22. Normalize a 5x5 random matrix

In [20]:
np.random.seed(0)
x = np.random.randint(10, size = (5,5))
print(x)
maxmin = x.max(),x.min()
maxmin
x= (x-xmin)/(xmax-xmin)
print(x)

[[5 0 3 3 7]
 [9 3 5 2 4]
 [7 6 8 8 1]
 [6 7 7 8 1]
 [5 9 8 9 4]]
[[ 0.44444444  1.          0.66666667  0.66666667  0.22222222]
 [-0.          0.66666667  0.44444444  0.77777778  0.55555556]
 [ 0.22222222  0.33333333  0.11111111  0.11111111  0.88888889]
 [ 0.33333333  0.22222222  0.22222222  0.11111111  0.88888889]
 [ 0.44444444 -0.          0.11111111 -0.          0.55555556]]


23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) 

In [27]:
color = np.dtype([("r", np.ubyte, 1),
                  ("g", np.ubyte, 1),
                  ("b", np.ubyte, 1),
                  ("a", np.ubyte, 1)])

C:\Users\Dell\AppData\Local\Temp\ipykernel_12264\2911720781.py:1: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  color = np.dtype([("r", np.ubyte, 1),


24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product)

In [25]:
y= np.dot(np.ones((5,3)), np.ones((3,2)))
print (y)

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


25. Given a 1D array, negate all elements which are between 3 and 8, in place. 

In [29]:
Z = np.arange(11)
Z[(3 < Z) & (Z <= 8)] *= -1
print(Z)

[ 0  1  2  3 -4 -5 -6 -7 -8  9 10]


26. What is the output of the following script?
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

9
10

27. Consider an integer vector Z, which of these expressions are legal?
Z**Z         legal
2 << Z >>   legal2
Z <-       legal Z
1         legalj*Z
Z        legal/1/1
        ilegalZ<Z>Z

In [43]:
Z = np.random.randint(5,size=(3,3))
Z

array([[3, 3, 2],
       [4, 2, 0],
       [0, 4, 0]])

In [49]:
Z**Z

array([[ 27,  27,   4],
       [256,   4,   1],
       [  1, 256,   1]])

28. What are the result of the following expressions?
np.array(0) / np.array(0)      = nan
np.array(0) // np.array(0     = 0)
np.array([np.nan]).astype(int).astype(floa  = array([-2.14748365e+09])t)

In [51]:
xy = np.array(0)
xy

array(0)

In [55]:
xy//xy

C:\Users\Dell\AppData\Local\Temp\ipykernel_12264\4266615255.py:1: RuntimeWarning: divide by zero encountered in floor_divide
  xy//xy


0

29. How to round away from zero a float array ?

In [57]:
Z = np.random.uniform(-10,+10,10)
print(Z)
print (np.copysign(np.ceil(np.abs(Z)), Z))

[-7.42147405 -3.69143298 -2.72578458  1.40393541 -1.22796973  9.76747676
 -7.95910379 -5.82246488 -6.77380964  3.06216651]
[-8. -4. -3.  2. -2. 10. -8. -6. -7.  4.]


30. How to find common values between two arrays?

In [67]:
np.random.seed(0)
Z1 = np.random.randint(0,12,8)
Z2 = np.random.randint(0,10,10)
print(Z1)
print(Z2)
print(np.intersect1d(Z1,Z2))

[ 5  0  3 11  3  7  9  3]
[5 2 4 7 6 8 8 1 6 7]
[5 7]
