1. Import the numpy package under the name np 

In [1]:
import numpy as np

2. Print the numpy version and the configuration

In [2]:
np.__version__

'1.26.4'

3. Create a null vector of size 10 

In [5]:
np.zeros(10, dtype=int )

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

4. How to find the memory size of any array 

In [6]:
arr = np.arange(10)
arr.itemsize

4

5. How to get the documentation of the numpy add function from the command line?

In [8]:
In [4]: np?

Type:        module
String form: <module 'numpy' from 'C:\\Users\\Dell\\Desktop\\ZINDUA\\Data_Analysis\\venv\\Lib\\site-packages\\numpy\\__init__.py'>
File:        c:\users\dell\desktop\zindua\data_analysis\venv\lib\site-packages\numpy\__init__.py
Docstring:  
NumPy
=====

Provides
  1. An array object of arbitrary homogeneous items
  2. Fast mathematical operations over arrays
  3. Linear Algebra, Fourier Transforms, Random Number Generation

How to use the documentation
----------------------------
Documentation is available in two forms: docstrings provided
with the code, and a loose standing reference guide, available from
`the NumPy homepage <https://numpy.org>`_.

We recommend exploring the docstrings using
`IPython <https://ipython.org>`_, an advanced Python shell with
TAB-completion and introspection capabilities.  See below for further
instructions.

The docstring examples assume that `numpy` has been imported as ``np``::

  >>> import numpy as np

Code snippets are indicated 

6. Create a null vector of size 10 but the fifth value which is 1

In [10]:
x = np.zeros(10, dtype=int)
x[4] = 1
x

array([0, 0, 0, 0, 1, 0, 0, 0, 0, 0])

7. Create a vector with values ranging from 10 to 49

In [12]:
y = np.arange(10,50)
y

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

8. Reverse a vector (first element becomes last)

In [13]:
y[::-1]

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

9. Create a 3x3 matrix with values ranging from 0 to 8 

In [16]:
z = np.arange(0,9).reshape(3,3)
z

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

10. Find indices of non-zero elements from [1,2,0,0,4,0]

In [18]:
xy = np.array([1,2,0,0,4,0])
np.where(xy!=0)

(array([0, 1, 4], dtype=int64),)

11. Create a 3x3 identity matrix

In [19]:
np.full((3,3),5)

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

12. Create a 3x3x3 array with random values

In [22]:
np.random.randint(10, size = (3,3,3))

array([[[3, 0, 7],
        [8, 2, 9],
        [5, 9, 7]],

       [[2, 9, 1],
        [0, 9, 3],
        [8, 9, 5]],

       [[5, 2, 6],
        [9, 4, 8],
        [1, 4, 4]]])

In [ ]:
13. Create a 10x10 array with random values and find the minimum and maximum values

In [23]:
arr2 = np.random.randint(100, size = (10,10))
arr2

array([[28, 22, 17, 13, 64, 30,  4, 96, 86, 58],
       [59, 19, 61, 13, 85, 47, 59, 91, 67, 61],
       [89, 44, 63, 72, 64, 63, 66, 30, 43, 16],
       [33, 74, 36, 34, 13, 55, 42, 85, 61, 41],
       [ 7, 14, 18, 37, 69, 95, 68, 67, 97, 66],
       [22, 36, 62, 12, 88, 38, 53, 72, 35, 62],
       [77, 54,  7, 64, 72, 91, 36, 88, 11, 47],
       [15, 80, 62, 94, 21, 70, 97, 30, 67, 41],
       [77, 63, 37, 86, 93, 88, 93, 14, 54, 68],
       [20, 88,  6, 48, 66, 18, 70, 61, 51, 21]])

In [25]:
print("the min value is :", np.min(arr2))
print("the min value is :" ,np.max(arr2))

the min value is : 4
the min value is : 97


14. Create a random vector of size 30 and find the mean value

In [27]:
v1 = np.random.randint(100, size = 30)
v1

array([95, 14, 82, 46, 17, 66, 72,  7, 78, 19,  0, 83, 96, 31, 19, 56,  6,
       78, 99, 41, 48, 45, 16, 26, 41, 48, 27, 63, 13,  5])

In [29]:
print("the mean is :", np.mean(v1))

the mean is : 44.56666666666667


15. Create a 2d array with 1 on the border and 0 inside 

In [31]:
arr3 = np.ones((5,5),dtype = int)
arr3

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [32]:
arr3[1:-1,1:-1] = 0
arr3

array([[1, 1, 1, 1, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 1, 1, 1, 1]])